In [1]:
import googlemaps

In [2]:
gmaps_key='AIzaSyDHfe4avvkDNqDQTDWZiLaTZrwLRUlKafs'
gmaps= googlemaps.Client(key=gmaps_key)

In [30]:
gmaps.geocode('서울중부경찰서',language='ko')[0]

{'address_components': [{'long_name': '２７',
   'short_name': '２７',
   'types': ['premise']},
  {'long_name': '수표로',
   'short_name': '수표로',
   'types': ['political', 'sublocality', 'sublocality_level_4']},
  {'long_name': '을지로동',
   'short_name': '을지로동',
   'types': ['political', 'sublocality', 'sublocality_level_2']},
  {'long_name': '중구',
   'short_name': '중구',
   'types': ['political', 'sublocality', 'sublocality_level_1']},
  {'long_name': '서울특별시',
   'short_name': '서울특별시',
   'types': ['administrative_area_level_1', 'political']},
  {'long_name': '대한민국', 'short_name': 'KR', 'types': ['country', 'political']},
  {'long_name': '100-032', 'short_name': '100-032', 'types': ['postal_code']}],
 'formatted_address': '대한민국 서울특별시 중구 을지로동 수표로 27',
 'geometry': {'location': {'lat': 37.5636465, 'lng': 126.9895796},
  'location_type': 'ROOFTOP',
  'viewport': {'northeast': {'lat': 37.56499548029149,
    'lng': 126.9909285802915},
   'southwest': {'lat': 37.56229751970849, 'lng': 126.9882306197085}}},
 'place_id': 'ChIJc-9q5uSifDURLhQmr5wkXmc',
 'plus_code': {'compound_code': 'HX7Q+FR 대한민국 서울특별시',
  'global_code': '8Q98HX7Q+FR'},
 'types': ['establishment', 'point_of_interest', 'police']}

In [4]:
import numpy as np
import pandas as pd

In [8]:
crime_police= pd.read_csv("C:/anaconda/DataScience/data/02. crime_in_Seoul.csv", thousands=',', encoding='euc-kr')
crime_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [9]:
station_name=[]

for name in crime_police['관서명']:
    station_name.append('서울' + str(name[:-1])+ '경찰서')

station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [48]:
station_address=[]
station_lat=[]
station_lng=[]

for name in station_name:
    tmp= gmaps.geocode(name,language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    
    tmp_loc= tmp[0].get('geometry')
    station_lat.append(tmp_loc['location']['lat'])
    station_lng.append(tmp_loc['location']['lng'])
    
    print(name + '-->' + tmp[0].get('formatted_address'))

서울중부경찰서-->대한민국 서울특별시 중구 을지로동 수표로 27
서울종로경찰서-->대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46
서울남대문경찰서-->대한민국 서울특별시 중구 회현동 한강대로 410
서울서대문경찰서-->대한민국 서울특별시 서대문구 충현동 통일로 113
서울혜화경찰서-->대한민국 서울특별시 종로구 인의동 창경궁로 112-16
서울용산경찰서-->대한민국 서울특별시 용산구 원효로1가 백범로 329
서울성북경찰서-->대한민국 서울특별시 성북구 삼선동5가 301
서울동대문경찰서-->대한민국 서울특별시 동대문구 청량리동 약령시로21길 29
서울마포경찰서-->대한민국 서울특별시 마포구 아현동 618-1
서울영등포경찰서-->대한민국 서울특별시 영등포구 문래동3가 경인로 759
서울성동경찰서-->대한민국 서울특별시 성동구 행당동 왕십리광장로 9
서울동작경찰서-->대한민국 서울특별시 동작구 노량진1동 노량진로 148
서울광진경찰서-->대한민국 서울특별시 광진구 구의동 자양로 167
서울서부경찰서-->대한민국 서울특별시 은평구 대조동 통일로 757
서울강북경찰서-->대한민국 서울특별시 강북구 번1동 오패산로 406
서울금천경찰서-->대한민국 서울특별시 금천구 시흥동 190
서울중랑경찰서-->대한민국 서울특별시 중랑구 신내1동 신내역로3길 40-10
서울강남경찰서-->대한민국 서울특별시 강남구 대치동 998
서울관악경찰서-->대한민국 서울특별시 관악구 봉천동
서울강서경찰서-->대한민국 서울특별시 양천구 신월동 화곡로 73
서울강동경찰서-->대한민국 서울특별시 강동구 성내1동 성내로 57
서울종암경찰서-->대한민국 서울특별시 성북구 종암동 종암로 135
서울구로경찰서-->대한민국 서울특별시 구로구 가마산로 235
서울서초경찰서-->대한민국 서울특별시 서초구 서초3동 반포대로 179
서울양천경찰서-->대한민국 서울특별시 양천구 신정6동 목동동로 99
서울송파경찰서-->대한민국 서울특별시 송파구 가락본동 9
서울노원경찰서-->대한민국 서울특별시 노원구 하계동 노원로 283
서울방배경찰서-->대한민국 서울특별시 서초구 방배본동 동작대로 204
서울은평경찰서-->대한민국 서울특별시 은평구 불광동 연서로 365
서울도봉경찰서-->대한민국 서울특별시 도봉구 창4동 노해로 403
서울수서경찰서-->대한민국 서울특별시 강남구 개포동 개포로 617

In [67]:
gu_name=[]
for name in station_address:
    tmp=name.split()
    
    tmp_gu= [gu for gu in tmp if gu[-1]=='구'][0]
    
    gu_name.append(tmp_gu)
    
crime_police['구별']=gu_name
crime_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [69]:
crime_police.loc[crime_police['관서명']=='금천서',['구별']]='관악구'

In [73]:
crime_police.loc[crime_police['관서명']=='금천서',['구별']]='금천구'

In [77]:
crime_police.to_csv('C:/anaconda/DataScience/data/02. crime_in_seoul_gu', sep=',', encoding='utf-8')

In [78]:
crime_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [80]:
crime_police_raw= pd.read_csv('C:/anaconda/DataScience/data/02. crime_in_seoul_gu',encoding='utf-8',index_col=0)
crime_police_raw.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [83]:
crime= pd.pivot_table(crime_police_raw, index='구별', aggfunc=np.sum)
crime.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
관악구    221    320     14     12      8      9    827   2706   2642   3298
광진구    220    240     26     14      4      4   1277   3026   2180   2625

In [85]:
crime['강간검거율']=crime['강간 검거']/crime['강간 발생']*100
crime['강도검거율']=crime['강도 검거']/crime['강도 발생']*100
crime['살인검거율']=crime['살인 검거']/crime['살인 발생']*100
crime['절도검거율']=crime['절도 검거']/crime['절도 발생']*100
crime['폭력검거율']=crime['폭력 검거']/crime['폭력 발생']*100

del crime['강간 검거']
del crime['강도 검거']
del crime['살인 검거']
del crime['절도 검거']
del crime['폭력 검거']

crime.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,185.714286,100.000000,42.200925,83.047619

In [97]:
con_list= ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']

for column in con_list:
    crime.loc[crime[column]>100, column]=100

crime.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [100]:
crime.rename(columns={'강간 발생':'강간','강도 발생':'강도','절도 발생':'절도','폭력 발생':'폭력','살인 발생':'살인'},inplace=True)
crime.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619

In [105]:
from sklearn import preprocessing

col=['강간','강도','살인','절도','폭력']

x= crime[col].values
min_max_scaler= preprocessing.MinMaxScaler()

x_scaled= min_max_scaler.fit_transform(x.astype(float))
crime_norm= pd.DataFrame(x_scaled, columns=col, index=crime.index)

col2=['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_norm[col2]=crime[col2]
crime_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619

In [107]:
result_cctv= pd.read_csv('C:/anaconda/DataScience/data/01. CCTV_result.csv',encoding='utf-8',index_col='구별')
crime_norm[['인구수', 'CCTV']]= result_cctv[['인구수', '소계']]
crime_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV
구별,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707

In [108]:
col=['강간','강도','살인','절도','폭력']
crime_norm['범죄']= np.sum(crime_norm[col], axis=1)
crime_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄
구별,,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,4.472701
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,1.116551
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,1.494746
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,2.613667
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707,2.034438

In [109]:
col=['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']
crime_norm['검거']= np.sum(crime_norm[col],axis=1)
crime_norm.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율,인구수,CCTV,범죄,검거
구별,,,,,,,,,,,,,,
강남구,1.000000,0.941176,0.916667,0.953472,0.661386,77.728285,85.714286,76.923077,42.857143,86.484594,570500.0,2780,4.472701,369.707384
강동구,0.155620,0.058824,0.166667,0.445775,0.289667,78.846154,100.000000,75.000000,33.347422,82.890855,453233.0,773,1.116551,370.084431
강북구,0.146974,0.529412,0.416667,0.126924,0.274769,82.352941,92.857143,100.000000,43.096234,88.637222,330192.0,748,1.494746,406.943540
관악구,0.628242,0.411765,0.583333,0.562094,0.428234,69.062500,100.000000,88.888889,30.561715,80.109157,525515.0,1496,2.613667,368.622261
광진구,0.397695,0.529412,0.166667,0.671570,0.269094,91.666667,100.000000,100.000000,42.200925,83.047619,372164.0,707,2.034438,416.915211